const Restaurants = [
  {
    id: 1,
    name: 'The Flavourful Feast',
    image: require('../../Components/AppImages/FlavourFeast.jpg'),
    address: '123 Vine Street, Parktown',
    description: 'Experience a world of flavors in every bite at The Flavourful Feast.',
    phoneNumber: '123-456-7890',
    website: 'www.flavourfulfeast.com',
    email: 'info@flavourfulfeast.com',
  },
  {
    id: 2,
    name: 'The Gourmet Galley',
    image: require('../../Components/AppImages/GourmetGalley.jpg'),
    address: '321 Maze Street, Hydepark',
    description: 'Indulge in gourmet delights by the sea at The Gourmet Galley.',
    phoneNumber: '234-567-8901',
    website: 'www.gourmetgalley.net',
    email: 'contact@gourmetgalley.net',
  },
  {
    id: 3,
    name: 'Culinary Cove',
    image: require('../../Components/AppImages/CulinaryCove.jpg'),
    address: '456 Salomne Street, Rosebank',
    description: 'A hidden gem for food enthusiasts, Culinary Cove offers culinary delights in a tranquil setting.',
    phoneNumber: '345-678-9012',
    website: 'www.culinarycove.org',
    email: 'info@culinarycove.org',
  },
  {
    id: 4,
    name: 'The Epicurean Emporium',
    image: require('../../Components/AppImages/EpicureanEporium.jpg'),
    address: '654 Jan Smuts Street, Milpark',
    description: 'Elevate your taste buds with the exquisite offerings at The Epicurean Emporium.',
    phoneNumber: '456-789-0123',
    website: 'www.epicureanemporium.com',
    email: 'contact@epicureanemporium.com',
  },
  {
    id: 5,
    name: 'The Savory Sanctuary',
    image: require('../../Components/AppImages/SovarySanctuary.jpg'),
    address: '789 Court yard Street, Aucklandpark',
    description: 'Find solace in the flavors of The Savory Sanctuary, where each dish is a culinary masterpiece.',
    phoneNumber: '567-890-1234',
    website: 'www.savorysanctuary.co.za',
    email: 'info@savorysanctuary.co.za',
  },
  {
    id: 6,
    name: 'The Delectable Den',
    image: require('../../Components/AppImages/DelectableDen.jpg'),
    address: '987 Plain Street, Parkview',
    description: 'Step into The Delectable Den and savor the art of fine dining in a cozy den-like ambiance.',
    phoneNumber: '678-901-2345',
    website: 'www.delectabledendining.com',
    email: 'reservations@delectabledendining.com',
  },
  {
    id: 7,
    name: 'The Gastronomic Grove',
    image: require('../../Components/AppImages/GastronomicGrove.jpg'),
    address: '963 Oak Street, Melrose',
    description: 'Embark on a gastronomic journey through the lush and exquisite offerings of The Gastronomic Grove.',
    phoneNumber: '789-012-3456',
    website: 'www.gastronomicgrove.co.za',
    email: 'info@gastronomicgrove.co.za',
  },
  {
    id: 8,
    name: 'The Culinary Cottage',
    image: require('../../Components/AppImages/CllinaryCottage.jpg'),
    address: '258 Mitchlle Place Street, Rosebank',
    description: 'Visit The Culinary Cottage for a homely experience with a touch of gourmet sophistication.',
    phoneNumber: '890-123-4567',
    website: 'www.culinary-cottage.com',
    email: 'contact@culinary-cottage.com',
  },
  {
    id: 9,
    name: 'The Bite-Sized Bistro',
    image: require('../../Components/AppImages/BitesizeBistro.jpg'),
    address: '147 Natures Avenue, Dunkeld',
    description: 'Satisfy your cravings with small but mighty flavors at The Bite-Sized Bistro.',
    phoneNumber: '901-234-5678',
    website: 'www.bitesizebistro.com',
    email: 'info@bitesizebistro.com',
  },
  {
    id: 10,
    name: 'The Mouthwatering Mezzanine',
    image: require('../../Components/AppImages/Mouthwatering.jpg'),
    address: '852 North Street, Sandton',
    description: 'Elevate your dining experience to new heights at The Mouthwatering Mezzanine.',
    phoneNumber: '012-345-6789',
    website: 'www.mouthwateringmezzanine.com',
    email: 'reservations@mouthwateringmezzanine.com',
  },
  {
    id: 11,
    name: 'Dine',
    image: require('../../Components/AppImages/TheEats.jpg'),
    address: '741 Mountain View Street, RandPark Ridge',
    description: 'At Dine, every dish is a masterpiece, and every meal is a memorable experience.',
    phoneNumber: '123-456-7890',
    website: 'www.dine.com',
    email: 'contact@dine.com',
  },
  {
    id: 12,
    name: 'Taste',
    image: require('../../Components/AppImages/Taste.jpg'),
    address: '028 Chris Street, Lynden',
    description: 'Discover the true essence of taste at Taste, where each bite tells a unique story.',
    phoneNumber: '234-567-8901',
    website: 'www.taste.net',
    email: 'info@taste.net',
  },
];

export default Restaurants;
